# GET /
GET http://localhost:3000 HTTP/1.1

### POST /
POST http://localhost:3000 HTTP/1.1
Content-Type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### POST /auth/login
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "123456$"
}

### POST /auth/register
POST http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json

{
    "email": "test@example.com",
    "fullName": "Test Example",
    "password": "123456$"
}

### User Profile

GET http://localhost:3000/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxMzMxMjA3NywiZXhwIjoxNzEzMzE1Njc3fQ.B9jNVs1kp8KWAe6KODrObX8djN5MnvlnfqeHBBYs8e8

### Get categories
GET http://localhost:3000/categories HTTP/1.1

### Create category
POST http://localhost:3000/categories HTTP/1.1
content-type: application/json

{
    "name": "Salary",
    "type": "income"
}

### Get category by ID
GET http://localhost:3000/categories/1 HTTP/1.1

### Update category
PUT http://localhost:3000/categories/1 HTTP/1.1
content-type: application/json

{
    "name": "Salary",
    "type": "income"
}

### Delete category
DELETE http://localhost:3000/categories/1 HTTP/1.1

### Get all records
GET http://localhost:3000/records HTTP/1.1

### Get all expenses
GET http://localhost:3000/records/expense HTTP/1.1

### Get all incomes
GET http://localhost:3000/records/income HTTP/1.1

### Create record
POST http://localhost:3000/records HTTP/1.1
content-type: application/json

{
    "amount": 800000,
    "category": "Salary",
    "date": "2023-03-01T09:00:00",
    "deleted": false,
    "name": "Salary",
    "type": "income"
}

### Get all expenses
GET http://localhost:3000/records/record/1 HTTP/1.1

### Get all expenses
PUT http://localhost:3000/records/1 HTTP/1.1
content-type: application/json

{
    "amount": 5000,
    "category": "Food",
    "date": "2023-03-01T09:00:00",
    "deleted": false,
    "name": "Food friday",
    "type": "expense"
}

### Move to trash
DELETE http://localhost:3000/records/trash/1 HTTP/1.1

### Delete permanently
DELETE http://localhost:3000/records/1 HTTP/1.1
